(function(root){
const arr=v=>Array.isArray(v)?v:[],obj=v=>v&&typeof v==='object'?v:{},txt=v=>typeof v==='string'?v:v?.claim||v?.label||v?.description||v?.title||v?.issue||v?.work||v?.name||'';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>v===null||v===undefined||v===''?'À confirmer':new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(v);
const plain=v=>txt(v).replace(/\([^)]*\.pdf[^)]*\)/gi,'').replace(/\bDDT\b/g,'dossier de diagnostics').replace(/\bDVF\+?\b/g,'ventes enregistrées').replace(/\bPPPT\b/g,'projet de plan de travaux').replace(/\bDTG\b/g,'bilan technique de l’immeuble').replace(/\bPV\b/g,'compte rendu').replace(/quote-part/gi,'part à payer').replace(/exposition financière/gi,'dépenses possibles').replace(/gouvernance/gi,'gestion de l’immeuble').replace(/fonds Alur/gi,'épargne de la copropriété pour les travaux').replace(/\s+/g,' ').trim();
const list=(items,empty='Aucune information établie dans ce dossier.')=>arr(items).length?'<ul>'+arr(items).map(x=>'<li>'+esc(plain(x))+(x?.source?'<small>'+esc(x.source)+(x.page?' · page '+esc(x.page):'')+'</small>':'')+'</li>').join('')+'</ul>':'<p class="rv-muted">'+esc(empty)+'</p>';
const detail=(title,body)=>'<details class="rv-detail"><summary>'+esc(title)+'<span aria-hidden="true">＋</span></summary><div>'+body+'</div></details>';
function render(result){
 const a=obj(result.analysis),p=obj(a.property),m=obj(a.market),co=obj(a.copro),cm=obj(a.copro_metrics),works=obj(a.works),s=obj(result.scores),meta=obj(result.meta),docs=obj(a.documents),r=obj(a.risk_flags),ex=obj(a.executive_summary),v=obj(a.verdict);
 const quality=arr(meta.document_quality),rejected=arr(docs.rejected),partial=quality.filter(x=>x.quality!=='ok'),diagnosticPartial=partial.some(x=>/ddt|diag|dpe/i.test(x.name||''));
 const incomplete=partial.length>0||rejected.length>0||meta.degraded_mode;
 const ask=p.asking_price,low=m.estimate_low,high=m.estimate_high,hasMarket=ask>0&&low>0&&high>=low&&meta.dvf_status!=='unavailable';
 const above=hasMarket&&ask>high;const priceLine=hasMarket?(above?'Au-dessus des ventes de référence':ask<low?'Sous les ventes de référence':'Dans la fourchette des ventes de référence'):'Comparaison encore incomplète';
 const hasWorks=arr(works.voted).length>0||r.voted_major_works;const major=r.recurring_major_technical_issue||r.major_property_defect;
 const headline=incomplete?'Des vérifications restent nécessaires':major?'Des points importants à sécuriser':'L’essentiel avant votre décision';
 const caption=incomplete?'La lecture du dossier est incomplète. Les conclusions restent provisoires.':p.dpe_validity==='invalid'?'Obtenez un DPE valide avant de conclure sur l’énergie du logement.'+(above?' Le prix demandé dépasse les ventes de référence.':''):above?'Le prix demandé dépasse les ventes de référence. Vérifiez les différences d’état, de surface et de prestations.':plain(v.summary||ex.overview||'Retrouvez les points utiles et les vérifications à mener avant une offre.');
 const invalidDpe=p.dpe_validity==='invalid';
 const diagnosticOK=!diagnosticPartial&&!invalidDpe&&s.evidence_gate?.property===true;
 const homeNote=invalidDpe?'Le document affiche '+(p.dpe||'une classe à confirmer')+', mais indique un numéro ADEME absent et une non-validité. Demandez le DPE enregistré.':diagnosticPartial?'Le diagnostic n’a pas été entièrement lu. Impossible de conclure sur l’état du logement.':r.electrical_anomalies?'Une intervention électrique est à prévoir ; demandez un devis.':r.major_property_defect?'Un défaut important est signalé dans les documents.':diagnosticOK?'Consultez les diagnostics et les éventuelles interventions à prévoir.':'Les diagnostics restent à vérifier.';
 const coproNote=major?'Des problèmes techniques récurrents sont signalés. Vérifiez leur résolution et votre part à payer.':hasWorks?'Des travaux ont été décidés. Le montant restant à votre charge doit être confirmé.':'Les décisions de l’immeuble et les charges sont à consulter.';
 const actions=[];
 if(invalidDpe)actions.push(['Obtenir le DPE valide','Demander au diagnostiqueur la version enregistrée avec son numéro ADEME.']);
 else if(diagnosticPartial||!diagnosticOK)actions.push(['Faire vérifier les diagnostics','Relire le dossier complet avant de conclure sur l’énergie et les travaux du logement.']);
 if(hasWorks||major)actions.push(['Chiffrer les travaux à votre charge','Demander au syndic ce qui est voté, payé et reste à régler pour ce logement.']);
 if(p.occupied)actions.push(['Vérifier le bail en cours','Le logement est occupé : confirmer le loyer, les dates et les conditions de l’achat.']);
 if(above)actions.push(['Comprendre l’écart de prix','Comparer l’état, les annexes et les prestations aux ventes voisines avant de négocier.']);
 if(!s.evidence_gate?.copro&&!hasWorks&&!major)actions.push(['Obtenir les pièces de copropriété','Demander les derniers comptes rendus d’assemblée, les charges et les travaux décidés.']);
 for(const q of arr(a.questions_before_offer)){const question=plain(q);if(invalidDpe&&/DPE|ADEME/i.test(question))continue;if(actions.length<3&&!actions.some(x=>x[1]===question))actions.push(['Demander une confirmation',question])}
 const readCount=quality.filter(x=>x.quality==='ok').length,total=quality.length+rejected.length;
 const documentRows=quality.map(x=>'<li><span>'+esc(x.name)+'</span><b class="'+(x.quality==='ok'?'rv-good':'rv-amber')+'">'+(x.quality==='ok'?'Texte exploitable':'Lecture partielle')+'</b>'+(x.weak_pages?'<small>'+esc(x.weak_pages)+' page(s) avec trop peu de texte sur '+esc(x.pages)+'.</small>':'')+'</li>').join('')+rejected.map(x=>'<li>'+esc(txt(x))+'<b class="rv-amber">Non lu</b><small>'+esc(x.reason||'Lecture à reprendre')+'</small></li>').join('');
 const facts=arr(a.evidence).filter(x=>x.status==='FACT');
 const comp=arr(m.comparables).map(x=>'<tr><td>'+esc(x.label||'Vente voisine')+'</td><td>'+esc(x.date||'')+'</td><td>'+money(x.price)+'</td><td>'+esc(x.surface??'—')+' m²</td></tr>').join('');
 const surfaceLabel=p.surface_basis==='habitable'||(/surface habitable/i.test(arr(p.assets).map(txt).join(' '))&&/Carrez.{0,40}(?:manqu|pas fournie|non fournie)/i.test(p.property_analysis||''))?' m² habitables':' m²';
 const diagnosticBody=(diagnosticPartial?'<p class="rv-warning">Ces conclusions sont provisoires : le fichier a été lu partiellement.</p>':'')+list(p.diagnostics)+list(p.weaknesses,'')+(p.energy_cost_low!=null&&p.energy_cost_high!=null?'<p>Budget énergie indiqué : '+money(p.energy_cost_low)+' à '+money(p.energy_cost_high)+' par an'+(diagnosticPartial?' — à confirmer après relecture.':'.')+'</p>':'');
 return '<div class="rv-report"><header class="rv-intro"><span class="rv-eyebrow">VOTRE ACHAT EN CLAIR</span><h1>'+esc(p.address||p.title||'Votre projet immobilier')+'</h1><div class="rv-facts"><span>'+esc(p.surface_m2??'Surface à confirmer')+(p.surface_m2?surfaceLabel:'')+'</span>'+(p.rooms?'<span>'+esc(p.rooms)+' pièce'+(p.rooms>1?'s':'')+'</span>':'')+'<span>'+money(ask)+'</span>'+(p.occupied?'<span>Vendu occupé</span>':'')+'</div></header>'+
 '<section class="rv-decision '+(incomplete?'rv-incomplete':'')+'"><span class="rv-eyebrow">À RETENIR</span><h2>'+esc(headline)+'</h2><p>'+esc(caption)+'</p>'+(total?'<p class="rv-coverage">'+readCount+' / '+total+' fichiers au texte exploitable'+(partial.length?' · '+partial.length+' à relire':'')+'. <a href="#rv-documents">Voir la lecture des documents</a></p>':'')+'</section>'+
 '<div class="rv-three"><article class="rv-tile"><span class="rv-icon" aria-hidden="true">⌂</span><h2>Le logement</h2><b class="rv-amber">'+(diagnosticPartial?'Diagnostic à relire':invalidDpe?'DPE non valide':/^[A-G]$/.test(p.dpe||'')?'DPE '+esc(p.dpe):'À vérifier')+'</b><p>'+esc(homeNote)+'</p></article><article class="rv-tile"><span class="rv-icon" aria-hidden="true">€</span><h2>Le prix</h2><b class="'+(above?'rv-amber':'rv-blue')+'">'+esc(priceLine)+'</b><p>'+(hasMarket?'Ventes de référence : <strong>'+money(low)+' à '+money(high)+'</strong>.':'Pas assez d’éléments pour comparer.')+'</p><small>Repère de marché, pas une estimation personnalisée.'+(p.garage_extra?' Garage en supplément.':'')+'</small></article><article class="rv-tile"><span class="rv-icon" aria-hidden="true">▤</span><h2>L’immeuble</h2><b class="rv-amber">'+(hasWorks?'Travaux à chiffrer':'À vérifier')+'</b><p>'+esc(coproNote)+'</p>'+(cm.lot_annual_charges!=null?'<small>Charges du lot : '+money(cm.lot_annual_charges)+'/an, soit environ '+money(cm.lot_annual_charges/12)+'/mois.</small>':'')+'</article></div>'+
 '<section class="rv-actions"><h2>Vos '+Math.min(actions.length,3)+' prochaines actions</h2><ol>'+actions.slice(0,3).map(x=>'<li><b>'+esc(x[0])+'</b><p>'+esc(x[1])+'</p></li>').join('')+'</ol></section>'+
 '<section class="rv-further"><h2>Comprendre et vérifier</h2><p class="rv-muted">Ouvrez uniquement le sujet qui vous intéresse.</p>'+
 detail('Le logement et ses diagnostics',diagnosticBody)+
 detail('Les travaux et les charges de l’immeuble','<h3>Travaux décidés</h3>'+list(works.voted)+'<h3>Projets encore discutés</h3>'+list([...arr(works.discussed),...arr(works.recommended_pppt),...arr(works.rejected_or_postponed)])+'<h3>Charges et finances</h3><p>'+esc(plain(co.financial_analysis))+'</p><p>'+esc(plain(co.technical_analysis))+'</p>')+
 detail('Le prix et les ventes voisines','<p>'+esc(plain(m.analysis||m.positioning))+'</p><div class="rv-table"><table><thead><tr><th>Bien vendu</th><th>Date</th><th>Prix</th><th>Surface</th></tr></thead><tbody>'+comp+'</tbody></table></div><p>'+esc(plain(a.negotiation?.recommended_strategy))+'</p>')+
 (p.occupied?detail('Le bail et les revenus locatifs','<p>Loyer hors charges : '+money(p.rent_excl_charges)+'/mois.</p><p>Provisions sur charges : '+money(p.charges_provision)+'/mois.</p>'+list(facts.filter(x=>/bail|loyer|locataire/i.test(txt(x))))):'')+
 detail('Toutes les vérifications et leurs sources',list(a.questions_before_offer)+list(a.buyer_blocks?.before_offer_checks?.checks)+list(a.buyer_blocks?.before_offer_checks?.inconsistencies)+list(facts))+
 '<div id="rv-documents">'+detail('Lecture des documents · '+total+' fichiers','<p>« Texte exploitable » signifie que la lecture a produit du texte. Cela ne certifie ni son exactitude, ni l’absence de problème dans le bien.</p><ul class="rv-doc-list">'+documentRows+'</ul><h3>Autres pièces à obtenir</h3>'+list(docs.missing_or_to_obtain)+list(docs.quality_notes))+'</div>'+
 detail('Comment les notes sont calculées',root.rvScoreDetailsHTML?root.rvScoreDetailsHTML(s):'<p>Notes non disponibles.</p>')+
 '</section><footer class="rv-disclaimer">Synthèse des informations reçues. Une information manquante n’est pas un défaut du bien. Les points non vérifiés restent à confirmer avant l’achat.</footer></div>';
}
root.rvReportHTML=render;
})(typeof window==='undefined'?globalThis:window);
